# Generated by Django 5.1.4 on 2024-12-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0004_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='encrypted_pin',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
